/*
 * Actieplan Managementletter 2025 — Concern voor Werk
 * ----------------------------------------------------------------------------
 * DIT BESTAND IS DE GEDEELDE BRON VAN WAARHEID voor het monitoring-dashboard.
 *
 * Status bijwerken kan op twee manieren:
 *   1) Open het dashboard, klik op “Bewerken”, pas status/notities aan en klik
 *      op “Exporteer data.js”. Vervang dit bestand door de download en commit.
 *   2) Pas hieronder handmatig de velden “status”, “notitie” en “bijgewerkt” aan.
 *
 * Toegestane status-waarden: “Open” (= Niet gestart), “Opgestart”, “Afgerond”.
 * Datums in formaat JJJJ-MM-DD.
 */

window.MONITOR_CONFIG = {
  title: "Actieplan Managementletter 2025",
  subtitle: "Concern voor Werk · Opvolging bevindingen accountant",
  kicker: "Monitoring · Voortgangsbewaking",
  peildatum: "2026-06-23",
  accent: "#0f766e"
};

window.ACTIES = [
  {
    "id": "P01",
    "thema": "Inkoop",
    "entiteit": "NV",
    "prioriteit": "Hoog",
    "bron": "Detailbevinding 1",
    "owner": "Manager Financiële Administratie (Dennis) + Inkoopcoördinator",
    "deadline": "2026-04-30",
    "status": "Open",
    "bijgewerkt": "",
    "notitie": "",
    "bevinding": "Budgethoudersregeling ontbreekt/ is niet formeel vastgelegd; onduidelijkheid in factuurprocuratie (m.n. productie).",
    "risico": "Ongeautoriseerde uitgaven; fouten in kostenclassificatie; risico op onrechtmatigheid.",
    "actie": "Stel formele Budgethoudersregeling op en configureer goedkeuringsmatrix in factuurprocuratiesysteem voor alle afdelingen; publiceer werkinstruction; train budgethouders.",
    "eersteStap": "Concept-regeling opstellen met RACI en limieten; afstemmen met Directie en RvC.",
    "kpi": "Vastgestelde regeling; aangepaste workflow live; log met autorisaties."
  },
  {
    "id": "P02",
    "thema": "Salarisadministratie (Gemeente)",
    "entiteit": "Gemeente",
    "prioriteit": "Hoog",
    "bron": "Detailbevinding 2",
    "owner": "HRM/Payroll coördinator + Manager FA",
    "deadline": "2026-04-30",
    "status": "Open",
    "bijgewerkt": "",
    "notitie": "",
    "bevinding": "Bruto-netto controle ontbreekt voor Wsw en SSF; checks & balances onvolledig.",
    "risico": "Onjuiste loonbetalingen en afdrachten; naheffingen/boetes; foutieve balansposities.",
    "actie": "Voer maandelijkse bruto-netto controle uit voor Wsw en SSF; 4-ogenprincipe vastleggen; herzie/actualiseer (D)VO met SLAs, rapportages en controlematrix.",
    "eersteStap": "Ontwerp controle-template; plan proefcontrole over laatste afgesloten maand.",
    "kpi": "Getekende controles; reconciliatie-overzichten; aangepaste DVO/werkafspraken."
  },
  {
    "id": "P03",
    "thema": "Montapak (projecten)",
    "entiteit": "NV",
    "prioriteit": "Middel",
    "bron": "Detailbevinding 3",
    "owner": "Manager Montapak + Controller Bedrijfsvoering",
    "deadline": "2026-09-30",
    "status": "Open",
    "bijgewerkt": "",
    "notitie": "",
    "bevinding": "Geen nacalculaties op orders; eerder als restrisico geaccepteerd.",
    "risico": "Onbekend rendement per order; risico op te lage prijzen.",
    "actie": "Pilot met ERP-orderadministratie (Exact) met eenvoudige nacalculatie op uren en materiaal bij top-10 orders; evalueer businesscase.",
    "eersteStap": "Selecteer pilot-orders; ontwerp eenvoudige nacalc-report. Exact Online.",
    "kpi": "Pilotrapportage; besluit over structurele invoering."
  },
  {
    "id": "P04",
    "thema": "Montapak (tarieven)",
    "entiteit": "NV",
    "prioriteit": "Hoog",
    "bron": "Detailbevinding 4",
    "owner": "Manager Montapak + Applicatiebeheer Exact",
    "deadline": "2026-09-30",
    "status": "Open",
    "bijgewerkt": "",
    "notitie": "",
    "bevinding": "Geen invoercontrole op (gewijzigde) tarieven; risico op foutieve facturatie.",
    "risico": "Onjuiste tarieven en facturen; opbrengsten fout.",
    "actie": "Implementeer masterdata-beheer: duale autorisatie voor nieuwe/gewijzigde tarieven, audit trail, periodieke steekproefcontrole; manager Montapak accordeert.",
    "eersteStap": "Inrichten goedkeuringsworkflow en activatie auditlog in systeem. Exact Online.",
    "kpi": "Log met tariefmutaties + goedkeuringen; steekproefrapport."
  },
  {
    "id": "P05",
    "thema": "Opbrengsten (breed)",
    "entiteit": "NV",
    "prioriteit": "Hoog",
    "bron": "Detailbevinding 5",
    "owner": "Sales/Accountmanagement + Controller + Juridische Zaken",
    "deadline": "2026-06-30",
    "status": "Open",
    "bijgewerkt": "",
    "notitie": "",
    "bevinding": "Volledigheid opbrengstverantwoording onvoldoende aantoonbaar; contracten/prijsafspraken niet eenduidig vastgelegd.",
    "risico": "Onvolledige opbrengsten in jaarrekening.",
    "actie": "Centraliseer contract- en kortingenregister (SharePoint) met verplichte metadata; jaarultimo ‘volledigheidsdossier’ per opbrengststroom; overweeg saldobevestigingen op risicogebieden.",
    "eersteStap": "Template contractregister + upload instructie publiceren; toewijzing eigenaren per stroom.",
    "kpi": "Compleet register; check op 100% contracten top-50 klanten; jaarultimo checklist."
  },
  {
    "id": "P06",
    "thema": "Kwekerij (verkoop)",
    "entiteit": "NV",
    "prioriteit": "Hoog",
    "bron": "Detailbevinding 6",
    "owner": "Manager Kwekerij + Commercieel MT-lid",
    "deadline": "2026-09-30",
    "status": "Open",
    "bijgewerkt": "",
    "notitie": "",
    "bevinding": "Functiescheiding ontbreekt; weekprijzen en kortingen door één persoon; afspraken zelden formeel vastgelegd.",
    "risico": "Ongewenste of nadelige prijsafspraken; afhankelijkheid en continuïteitsrisico.",
    "actie": "Introduceer functiescheiding: (1) prijszetting door team met mandaat; (2) klantcontact/onderhandelingen gescheiden; (3) kortingen >x% met MT-goedkeuring; standaard contract-/offertemodellen.",
    "eersteStap": "Opstellen prijs- en kortingsbeleid + autorisatiegrenzen; implementatie in CRM/ERP.",
    "kpi": "Getekend beleid; overzicht goedgekeurde kortingen; contractdossiers per klant."
  },
  {
    "id": "P07",
    "thema": "Jaarafsluiting & BTW",
    "entiteit": "NV",
    "prioriteit": "Hoog",
    "bron": "Detailbevinding 7",
    "owner": "Team FA + Salesfacturatie",
    "deadline": "2026-04-30",
    "status": "Open",
    "bijgewerkt": "",
    "notitie": "",
    "bevinding": "Factuurdata worden aangepast naar jaar van levering (antedatering).",
    "risico": "Onjuiste btw-periode; risico op boete belastingdienst.",
    "actie": "Stop antedateren; verwerk leveringen via transitoria/overlopende posten; actualiseer werkinstructie en monitor via steekproeven.",
    "eersteStap": "Nieuwe werkinstructie publiceren; training medewerkers facturatie.",
    "kpi": "% steekproeven zonder datumcorrectie; btw-aangiften conform factuurdatum."
  },
  {
    "id": "P08",
    "thema": "Spendanalyse & Aanbesteding",
    "entiteit": "NV",
    "prioriteit": "Hoog",
    "bron": "Managementsamenvatting",
    "owner": "Inkoop + Controller",
    "deadline": "2026-06-30",
    "status": "Open",
    "bijgewerkt": "",
    "notitie": "",
    "bevinding": "RvC benadrukte periodieke spendanalyse; 2025 nog niet uitgevoerd; aanbestedingsrisico onbekend.",
    "risico": "Niet-naleving aanbestedingsregels; gemiste besparingen.",
    "actie": "Voer spendanalyse 2025/2026 uit (Exact data, leveranciersclustering, drempeltoets); stel jaarlijkse cyclus en aanbestedingskalender vast.",
    "eersteStap": "Datadump crediteuren 2025; Power BI-rapport ontwerp.",
    "kpi": "Spendanalyserapport + acties; aanbestedingskalender vastgesteld."
  },
  {
    "id": "P09",
    "thema": "Fraudebeheersing (NV)",
    "entiteit": "NV",
    "prioriteit": "Hoog",
    "bron": "Paragraaf 3.3",
    "owner": "Directie + Controller Risicomanagement",
    "deadline": "2026-07-31",
    "status": "Open",
    "bijgewerkt": "",
    "notitie": "",
    "bevinding": "Geen organisatiebrede frauderisicoanalyse/fraudebeheersplan; integriteit beperkt zichtbaar in P&C-cyclus.",
    "risico": "Onvoldoende preventie/detectie; reputatie- en compliance risico.",
    "actie": "Voer integrale frauderisicoanalyse uit en stel Fraudebeheersplan op; veranker in P&C; periodieke evaluatie en rapportage aan RvC.",
    "eersteStap": "Kick-off met sleutelfuncties; keuze methode (COSO/NBA-handreiking).",
    "kpi": "Goedgekeurd plan; risicoregister; periodieke rapportage."
  },
  {
    "id": "P10",
    "thema": "IT-governance & AVG/NIS2 (NV)",
    "entiteit": "NV",
    "prioriteit": "Middel",
    "bron": "Paragraaf 3.4",
    "owner": "IT-Manager + CISO (extern) + Directie",
    "deadline": "2026-08-31",
    "status": "Open",
    "bijgewerkt": "",
    "notitie": "",
    "bevinding": "IT-bezetting kwetsbaar; rollen in ontwikkeling; Windows 365 en back-ups verbeterd; NIS2 nulmeting lopend.",
    "risico": "Continuïteits- en securityrisico; afhankelijkheid key persons.",
    "actie": "Rond NIS2 nulmeting af; stel IT-risicobeleid en roadmap op; verbeter kennisdeling; borg logische toegang, wijzigings- en continuïteitsbeheer; leveranciersmanagement formaliseren.",
    "eersteStap": "Plan oplevering nulmeting; benoem proceseigenaars per IT-controlegebied.",
    "kpi": "Nulmetingrapport; geaccordeerde roadmap; procedures/rollen gedocumenteerd."
  },
  {
    "id": "P11",
    "thema": "Rechtmatigheidsverantwoording (GR)",
    "entiteit": "GR",
    "prioriteit": "Hoog",
    "bron": "Paragraaf 5.2",
    "owner": "GR-secretaris + Controller GR",
    "deadline": "2026-07-31",
    "status": "Open",
    "bijgewerkt": "",
    "notitie": "",
    "bevinding": "Verantwoordingsgrens 1% (strikter); verordeningen en interne risicoanalyse/controleplan onvoldoende aangepast; voortgang interne controles achterloopt.",
    "risico": "Rechtmatigheidsfouten boven grens; onvolledige verantwoording.",
    "actie": "Actualiseer verordeningen; herijk risicoanalyse op 1%; stel planning/monitoring opdat interne controles begin febr. gereed zijn; rapporteer periodiek aan bestuur.",
    "eersteStap": "Sessie met bestuur om impact 1% vast te stellen; update controleplan.",
    "kpi": "Vastgestelde verordeningen; controleplan + voortgangsrapporten."
  },
  {
    "id": "P12",
    "thema": "VIC-functie (GR)",
    "entiteit": "GR",
    "prioriteit": "Hoog",
    "bron": "Paragraaf 5.2",
    "owner": "Bestuur GR + Directeur NV",
    "deadline": "2026-07-31",
    "status": "Open",
    "bijgewerkt": "",
    "notitie": "",
    "bevinding": "Geen onafhankelijke VIC-functie belegd; methodologische lat hoger.",
    "risico": "Onvoldoende onafhankelijk oordeel; risico op tekortschietende interne controle.",
    "actie": "Richt Verbijzonderde Interne Controle (VIC) in: profiel, positionering, onafhankelijkheid; plan werkzaamheden en rapportage-lijn naar bestuur.",
    "eersteStap": "Profiel opstellen en werving/aanwijzing starten (interim/extern mogelijk).",
    "kpi": "Aanstelling/mandaat; VIC-jaarplan en rapportageformat."
  },
  {
    "id": "P13",
    "thema": "Fraude/Misbruik/Oneigenlijk gebruik (GR)",
    "entiteit": "GR",
    "prioriteit": "Middel",
    "bron": "Paragraaf 5.3",
    "owner": "Bestuur GR + NV-directie",
    "deadline": "2026-09-30",
    "status": "Open",
    "bijgewerkt": "",
    "notitie": "",
    "bevinding": "FMO-beleid en risicoanalyse onvoldoende uitgewerkt; monitoring ontbreekt.",
    "risico": "Rechtmatigheidsrisico (M&O-criterium); reputatieschade.",
    "actie": "Stel FMO-beleid en risicoanalyse op; koppel aan NV-processen; stel monitoring en rapportage in (KPI's/incidentenregistratie).",
    "eersteStap": "Workshop FMO met proceseigenaren; definiëren beheersmaatregelen per regeling.",
    "kpi": "Vastgesteld beleid; kwartaalrapportages; incidentenlog."
  },
  {
    "id": "P14",
    "thema": "BIO/NIS2 en DVO's (GR ↔ NV ↔ Gemeente)",
    "entiteit": "Keten",
    "prioriteit": "Middel",
    "bron": "Paragraaf 5.4",
    "owner": "GR-bestuur + NV-directie + Gemeente Lelystad (ICT)",
    "deadline": "2026-07-31",
    "status": "Open",
    "bijgewerkt": "",
    "notitie": "",
    "bevinding": "DVO's voldoen niet; ketenverplichtingen mogelijk; beleid/nulmeting in ontwikkeling.",
    "risico": "Onduidelijke eisen en toezicht; non-compliance en beveiligingsrisico's.",
    "actie": "Actualiseer DVO's met heldere eisen (BIO/NIS2/AVG), contractmanagement en certificeringen; leg periodieke monitoring vast.",
    "eersteStap": "DVO-review sessie; opstellen concept addendum met KPI's en auditrechten.",
    "kpi": "Getekende DVO's; kwartaalrapportages; leveranciers-auditverslagen."
  },
  {
    "id": "P15",
    "thema": "Goedkeuringstolerantie & schattingen (GR)",
    "entiteit": "GR",
    "prioriteit": "Middel",
    "bron": "Paragraaf 5.5",
    "owner": "Controller GR",
    "deadline": "2026-08-31",
    "status": "Open",
    "bijgewerkt": "",
    "notitie": "",
    "bevinding": "BADO-wijziging: grondslag en optelling fouten+onzekerheden; minder ruimte; behoefte aan backtesting.",
    "risico": "Over-/onderschattingen; overschrijding tolerantie.",
    "actie": "Stel procedure op voor schattingen (onderbouwing, scenario's) en jaarlijkse backtesting; training voor opstellers.",
    "eersteStap": "Inventariseer materiële schattingen; ontwerp backtesting-template.",
    "kpi": "Dossier met onderbouwingen; backtesting-rapport."
  },
  {
    "id": "P16",
    "thema": "Personeelsverplichtingen (GR)",
    "entiteit": "GR",
    "prioriteit": "Hoog",
    "bron": "Paragraaf 5.6",
    "owner": "HRM + Controller GR",
    "deadline": "2026-06-30",
    "status": "Open",
    "bijgewerkt": "",
    "notitie": "",
    "bevinding": "Voorzieningen voor RVU (Wsw) en verlofsparen verplicht; analyse bovenwettelijk (stuwmeren) nodig; 2024 nog niet opgenomen.",
    "risico": "Onjuiste balans; onvolledige lasten; rechtmatigheid.",
    "actie": "Bereken en boek voorziening RVU en verlofsparen; analyseer bovenwettelijke verlofsaldi op 'niet-gelijke omvang' en 'overmatig'; stel tijdspaarplannen op voor hoge saldi.",
    "eersteStap": "Dataverzameling verlof- en leeftijdscohorten; methodiek vaststellen conform BBV-standpunt.",
    "kpi": "Memo onderbouwing; journaalposten; overzicht tijdspaarplannen."
  },
  {
    "id": "P17",
    "thema": "Auditvoorbereiding (GR/NV)",
    "entiteit": "GR / NV",
    "prioriteit": "Middel",
    "bron": "Paragraaf 6.1 + interne LOTLS",
    "owner": "Controller + Dossiereigenaren",
    "deadline": "Direct (doorlopend)",
    "status": "Open",
    "bijgewerkt": "",
    "notitie": "",
    "bevinding": "Jaarrekeningcontrole gepland; stukken 5 werkdagen vooraf gereed; LOTLS beschikbaar.",
    "risico": "Inefficiënte controle; vertraging oplevering.",
    "actie": "Werk met checklist en tijdslijn; wijs dossier-eigenaren aan; kwaliteitscheck voor aanlevering.",
    "eersteStap": "Planning finetunen en LOTLS-werkbladen vullen.",
    "kpi": "Volledig dossier T-5 werkdagen; auditfeedback beperkt."
  }
];
